using System.Text.Json;
using System.Text.RegularExpressions;
using MediatR;
using Microsoft.EntityFrameworkCore;
using YourExam.Application.Interfaces;
using YourExam.Domain.Entities;

namespace YourExam.Application.Features.QuestionTemplates.Commands.AutoGenerateTemplates;

public class AutoGenerateTemplatesCommandHandler : IRequestHandler<AutoGenerateTemplatesCommand, int>
{
    private readonly IApplicationDbContext _context;
    private readonly IOpenRouterService _openRouterService;

    public AutoGenerateTemplatesCommandHandler(IApplicationDbContext context, IOpenRouterService openRouterService)
    {
        _context = context;
        _openRouterService = openRouterService;
    }

    public async Task<int> Handle(AutoGenerateTemplatesCommand request, CancellationToken cancellationToken)
    {
        int totalQuantity = request.EasyQuantity + request.MediumQuantity + request.HardQuantity;
        if (totalQuantity <= 0) return 0;

        string typeName = request.QuestionType switch
        {
            1 => "Calculation",
            2 => "WordProblem",
            3 => "Comparison",
            4 => "FillInTheBlank",
            _ => throw new ArgumentException($"Invalid Question Type: {request.QuestionType}")
        };
        
        // Tìm thư mục gốc chứa thư mục "docs"
        string basePath = Directory.GetCurrentDirectory();
        while (!Directory.Exists(Path.Combine(basePath, "docs")) && Directory.GetParent(basePath) != null)
        {
            basePath = Directory.GetParent(basePath).FullName;
        }
        
        string promptFilePath = Path.Combine(basePath, "docs", "prompt", $"Lớp {request.GradeLevel}", $"Môn {request.Subject}", $"{typeName}.txt");

        if (!File.Exists(promptFilePath))
        {
            throw new FileNotFoundException($"Prompt file not found at {promptFilePath}");
        }

        string promptContent = await File.ReadAllTextAsync(promptFilePath, cancellationToken);

        // Customize prompt dynamically based on the requested quantities
        promptContent = Regex.Replace(promptContent, @"Hãy tạo ra \d+ template", $"Hãy tạo ra {totalQuantity} template");
        promptContent = Regex.Replace(promptContent, @"\*\*Dễ \(\d+ câu\):\*\*", $"**Dễ ({request.EasyQuantity} câu):**");
        promptContent = Regex.Replace(promptContent, @"\*\*Trung bình \(\d+ câu\):\*\*", $"**Trung bình ({request.MediumQuantity} câu):**");
        promptContent = Regex.Replace(promptContent, @"\*\*Khó \(\d+ câu\):\*\*", $"**Khó ({request.HardQuantity} câu):**");

        string quantityInstructions = $"\n\nBẮT BUỘC: Bạn phải sinh ra CHÍNH XÁC {totalQuantity} bài toán (object) JSON. KHÔNG ĐƯỢC THIẾU, KHÔNG ĐƯỢC THỪA.";
        promptContent += quantityInstructions;

        // Request generation
        string jsonResponse = await _openRouterService.GenerateContentAsync(promptContent, cancellationToken);
        
        // Sometimes AI wraps JSON in markdown ```json ... ```
        if (jsonResponse.StartsWith("```json"))
        {
            jsonResponse = jsonResponse.Substring(7);
            if (jsonResponse.EndsWith("```"))
            {
                jsonResponse = jsonResponse.Substring(0, jsonResponse.Length - 3);
            }
        }
        else if (jsonResponse.StartsWith("```"))
        {
            jsonResponse = jsonResponse.Substring(3);
            if (jsonResponse.EndsWith("```"))
            {
                jsonResponse = jsonResponse.Substring(0, jsonResponse.Length - 3);
            }
        }

        var options = new JsonSerializerOptions 
        { 
            PropertyNameCaseInsensitive = true,
            AllowTrailingCommas = true,
            ReadCommentHandling = JsonCommentHandling.Skip
        };
        var generatedTemplates = JsonSerializer.Deserialize<List<AutoGeneratedTemplateDto>>(jsonResponse.Trim(), options);

        if (generatedTemplates == null || !generatedTemplates.Any())
        {
            throw new Exception("AI returned empty or invalid JSON.");
        }

        var entities = generatedTemplates.Select(dto => new QuestionTemplate
        {
            Subject = dto.Subject,
            GradeLevel = dto.GradeLevel,
            Topic = dto.Topic,
            Difficulty = dto.Difficulty,
            QuestionType = dto.QuestionType,
            ContentTemplate = dto.ContentTemplate,
            AnswerFormula = dto.AnswerFormula,
            VariablesConfig = dto.VariablesConfig.GetRawText(),
            DistractorLogic = dto.DistractorLogic.ValueKind != JsonValueKind.Undefined ? dto.DistractorLogic.GetRawText() : "[]",
            IsActive = true
        }).ToList();

        _context.QuestionTemplates.AddRange(entities);
        await _context.SaveChangesAsync(cancellationToken);

        return entities.Count;
    }
}

public class AutoGeneratedTemplateDto
{
    public string Subject { get; set; } = string.Empty;
    public int GradeLevel { get; set; }
    public string Topic { get; set; } = string.Empty;
    public int Difficulty { get; set; }
    public int QuestionType { get; set; }
    public string ContentTemplate { get; set; } = string.Empty;
    public string AnswerFormula { get; set; } = string.Empty;
    public JsonElement VariablesConfig { get; set; }
    public JsonElement DistractorLogic { get; set; }
    public bool IsActive { get; set; } = true;
}
