using System.Text.Json;
using MediatR;
using Microsoft.EntityFrameworkCore;
using YourExam.Application.Interfaces;
using YourExam.Domain.Entities;

namespace YourExam.Application.Features.QuestionTemplates.Commands.AutoGenerateTemplates;

public class AutoGenerateTemplatesCommandHandler : IRequestHandler<AutoGenerateTemplatesCommand, int>
{
    private readonly IApplicationDbContext _context;
    private readonly IOpenRouterService _openRouterService;

    public AutoGenerateTemplatesCommandHandler(IApplicationDbContext context, IOpenRouterService openRouterService)
    {
        _context = context;
        _openRouterService = openRouterService;
    }

    public async Task<int> Handle(AutoGenerateTemplatesCommand request, CancellationToken cancellationToken)
    {
        int totalQuantity = request.EasyQuantity + request.MediumQuantity + request.HardQuantity;
        if (totalQuantity <= 0) return 0;

        string typeName = request.QuestionType == 1 ? "Trắc Nghiệm" : "Tự luận";
        
        // Tìm thư mục gốc chứa thư mục "docs"
        string basePath = Directory.GetCurrentDirectory();
        while (!Directory.Exists(Path.Combine(basePath, "docs")) && Directory.GetParent(basePath) != null)
        {
            basePath = Directory.GetParent(basePath).FullName;
        }
        
        string promptFilePath = Path.Combine(basePath, "docs", "prompt", $"Lớp {request.GradeLevel}", $"Môn {request.Subject}", $"{typeName}.txt");

        if (!File.Exists(promptFilePath))
        {
            throw new FileNotFoundException($"Prompt file not found at {promptFilePath}");
        }

        string promptContent = await File.ReadAllTextAsync(promptFilePath, cancellationToken);

        // Customize prompt dynamically based on the requested quantities
        string quantityInstructions = $"Sinh ra {request.EasyQuantity} câu Dễ (Difficulty: 1), {request.MediumQuantity} câu Trung bình (Difficulty: 2), và {request.HardQuantity} câu Khó (Difficulty: 3).";
        
        // Find the line that configures difficulty and replace it if we want, or just append our strict instruction at the top
        promptContent = promptContent.Replace("Sinh ra 2 câu Dễ (Difficulty: 1), 2 câu Trung bình (Difficulty: 2), và 1 câu Khó (Difficulty: 3 - đòi hỏi tư duy thêm bớt nhiều bước hoặc so sánh).", quantityInstructions);
        promptContent = promptContent.Replace("Sinh ra 4 câu Dễ (Difficulty: 1), 4 câu Trung bình (Difficulty: 2), và 2 câu Khó (Difficulty: 3 - đòi hỏi tư duy thêm bớt nhiều bước, nhân chia, hoặc kết hợp phép tính).", quantityInstructions);
        promptContent = promptContent.Replace("Sinh ra 4 câu Dễ (Difficulty: 1), 4 câu Trung bình (Difficulty: 2), và 2 câu Khó (Difficulty: 3 - đòi hỏi tư duy thêm bớt nhiều bước hoặc so sánh).", quantityInstructions);
        
        // Also replace the total count
        promptContent = promptContent.Replace("gồm 05 mẫu bài toán", $"gồm {totalQuantity} mẫu bài toán");
        promptContent = promptContent.Replace("05 bài toán này", $"{totalQuantity} bài toán này");
        promptContent = promptContent.Replace("gồm 10 mẫu bài toán", $"gồm {totalQuantity} mẫu bài toán");
        promptContent = promptContent.Replace("10 bài toán này", $"{totalQuantity} bài toán này");

        // Request generation
        string jsonResponse = await _openRouterService.GenerateContentAsync(promptContent, cancellationToken);
        
        // Sometimes AI wraps JSON in markdown ```json ... ```
        if (jsonResponse.StartsWith("```json"))
        {
            jsonResponse = jsonResponse.Substring(7);
            if (jsonResponse.EndsWith("```"))
            {
                jsonResponse = jsonResponse.Substring(0, jsonResponse.Length - 3);
            }
        }
        else if (jsonResponse.StartsWith("```"))
        {
            jsonResponse = jsonResponse.Substring(3);
            if (jsonResponse.EndsWith("```"))
            {
                jsonResponse = jsonResponse.Substring(0, jsonResponse.Length - 3);
            }
        }

        var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
        var generatedTemplates = JsonSerializer.Deserialize<List<AutoGeneratedTemplateDto>>(jsonResponse.Trim(), options);

        if (generatedTemplates == null || !generatedTemplates.Any())
        {
            throw new Exception("AI returned empty or invalid JSON.");
        }

        var entities = generatedTemplates.Select(dto => new QuestionTemplate
        {
            Subject = dto.Subject,
            GradeLevel = dto.GradeLevel,
            Topic = dto.Topic,
            Difficulty = dto.Difficulty,
            QuestionType = dto.QuestionType,
            ContentTemplate = dto.ContentTemplate,
            AnswerFormula = dto.AnswerFormula,
            VariablesConfig = dto.VariablesConfig.GetRawText(),
            DistractorLogic = dto.DistractorLogic.ValueKind != JsonValueKind.Undefined ? dto.DistractorLogic.GetRawText() : "[]",
            IsActive = dto.IsActive
        }).ToList();

        _context.QuestionTemplates.AddRange(entities);
        await _context.SaveChangesAsync(cancellationToken);

        return entities.Count;
    }
}

public class AutoGeneratedTemplateDto
{
    public string Subject { get; set; } = string.Empty;
    public int GradeLevel { get; set; }
    public string Topic { get; set; } = string.Empty;
    public int Difficulty { get; set; }
    public int QuestionType { get; set; }
    public string ContentTemplate { get; set; } = string.Empty;
    public string AnswerFormula { get; set; } = string.Empty;
    public JsonElement VariablesConfig { get; set; }
    public JsonElement DistractorLogic { get; set; }
    public bool IsActive { get; set; } = true;
}
